apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres-helm.fullname" . }}-init-db
  labels:
    {{- include "postgres-helm.labels" . | nindent 4 }}
data:
  init-databases.sh: |
    #!/bin/bash
    set -e

    echo "--- Running custom initialization script ---"

    {{- range .Values.postgres.databases }}
    echo "Creating database '{{ .name }}'"
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
        CREATE DATABASE {{ .name }};
    EOSQL

    {{- if .file }}
    echo "Loading data into '{{ .name }}' from '{{ .file }}'"
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "{{ .name }}" < "/sql-scripts/{{ .file }}"
    {{- end }}

    {{- end }}

    echo "--- Custom initialization finished ---"
