apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres-helm.fullname" . }}-sql-scripts
  labels:
    {{- include "postgres-helm.labels" . | nindent 4 }}
data:
{{- (.Files.Glob "sql-scripts/*.sql").AsConfig | nindent 2 }}
